name       : yodl
version    : 4.03.03
release    : 3
source     :
    - https://gitlab.com/fbb-git/yodl/-/archive/4.03.03/yodl-4.03.03.tar.gz : f765e80b468bbf88647bbf157a7668be0bff6ded40d8733e1ade352e1e7b3343
homepage   : https://fbb-git.gitlab.io/yodl/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Yodl implements a pre-document language and tools to process it
description: |
    Yodl is a package that implements a pre-document language and tools to process it.  The idea of Yodl is that you write up a document in a pre-language, then use the tools (e.g. yodl2html) to convert it to some final document language. Current converters are for HTML, ms, man, LaTeX, a simple txt converter and an experimental XML converter.  Main document types are "article", "book", "letter", "manpage" and  "report". The Yodl document language is designed to be easy to use and extensible.
builddeps  :
    - icmake
build      : |
    cd yodl
    ./build programs
    ./build macros
    ./build man
install    : |
    cd yodl
    ./build install programs %installroot%
    ./build install macros %installroot%
    ./build install man %installroot%
